import os

structure = [
    "game/project.godot",
    "game/src/core/bootstrap/GameInitializer.gd",
    "game/src/core/bootstrap/DependencyInjector.gd",
    "game/src/core/bootstrap/SystemsRegistry.gd",
    "game/src/core/events/EventBus.gd",
    "game/src/core/events/EventTypes.gd",
    "game/src/core/events/Event.gd",
    "game/src/core/state_machine/StateMachine.gd",
    "game/src/core/state_machine/State.gd",
    "game/src/core/state_machine/Transition.gd",
    "game/src/core/persistence/SaveManager.gd",
    "game/src/core/persistence/GameData.gd",
    "game/src/core/persistence/Serializer.gd",
    "game/src/game/systems/political/PoliticalSystem.gd",
    "game/src/game/systems/political/Coalition.gd",
    "game/src/game/systems/political/Faction.gd",
    "game/src/game/systems/political/PoliticalEvent.gd",
    "game/src/game/systems/economic/EconomicSystem.gd",
    "game/src/game/systems/economic/Treasury.gd",
    "game/src/game/systems/economic/Production.gd",
    "game/src/game/systems/economic/Trade.gd",
    "game/src/game/systems/threat/ThreatSystem.gd",
    "game/src/game/systems/threat/CIAAgent.gd",
    "game/src/game/systems/threat/EliteOpposition.gd",
    "game/src/game/systems/threat/MilitaryThreat.gd",
    "game/src/game/systems/time/TimeSystem.gd",
    "game/src/game/systems/time/Calendar.gd",
    "game/src/game/systems/time/DayPhases.gd",
    "game/src/game/entities/Region.gd",
    "game/src/game/entities/Ministry.gd",
    "game/src/game/entities/Reform.gd",
    "game/src/game/entities/Crisis.gd",
    "game/src/game/ai/AIDirector.gd",
    "game/src/game/ai/DecisionTree.gd",
    "game/src/game/ai/ThreatEvaluator.gd",
    "game/src/game/ai/DifficultyScaler.gd",
    "game/src/ui/screens/MainMenuScreen.gd",
    "game/src/ui/screens/DifficultyScreen.gd",
    "game/src/ui/screens/GameScreen.gd",
    "game/src/ui/screens/EndGameScreen.gd",
    "game/src/ui/components/MinistryCard.gd",
    "game/src/ui/components/NotificationPanel.gd",
    "game/src/ui/components/MapRegion.gd",
    "game/src/ui/components/AllendeSidebar.gd",
    "game/src/ui/popups/PopupBase.gd",
    "game/src/ui/popups/ReformPopup.gd",
    "game/src/ui/popups/CrisisPopup.gd",
    "game/src/ui/popups/RegionPopup.gd",
    "game/src/ui/theme/ChileanTheme.tres",
    "game/src/ui/theme/UIConstants.gd",
    "game/src/data/definitions/reforms.json",
    "game/src/data/definitions/crises.json",
    "game/src/data/definitions/events.json",
    "game/src/data/definitions/initial_state.json",
    "game/src/data/localization/text_es.json",
    "game/src/data/localization/text_en.json",
    "game/assets/visuals/backgrounds",
    "game/assets/visuals/portraits",
    "game/assets/visuals/icons",
    "game/assets/visuals/historical_photos",
    "game/assets/audio/music",
    "game/assets/audio/sfx",
    "game/assets/audio/ambient",
    "game/assets/fonts/main_font.tres",
    "game/assets/fonts/ui_font.tres",
    "game/tests/unit",
    "game/tests/integration",
    "game/tests/scenes",
]

for path in structure:
    if path.endswith(".gd") or path.endswith(".json") or path.endswith(".tres") or path.endswith(".godot"):
        os.makedirs(os.path.dirname(path), exist_ok=True)
        open(path, 'a').close()
    else:
        os.makedirs(path, exist_ok=True)